sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: T2767oSe7jvv5ffRl5izVLnqj1DziAuNiG8yk53YYWdYLZewAGKxpTgrSsaY1CDic/jr73Giz4qu5Edhu+aIEk9+UkCikaluCk0McskN8pfbBMyqNYyqrVO8mMWt0+nuaG1vEo5gSLnyW3zDISG8FSW+FfQ8FV+0DYR0vDE5q9AepPKUSA6msJdmPcHVj+xrdqWZiMOnV0sC8VtKqpVfC/6L66T5Ad/8iBsGs4tqm6v+hdNjvjexLqDBaXfLkdwccZGWNZWwhqYBWGgYZcUUPg6TMWQhcbKcgYhA16PlHu5TDWQR+vC6rgy+lOwFWvvYoygCK7GpR4641ZJJmvyBbDdhR1m7GXnEHVveT2hLxe5MV/U3MIkSnh3qUV3o35PvuU3IpLXdII6egNCDBuA2SBnJ17x2uaxdXcV6QysdF+hFSIzvy3/K447aj4gKC4FeUi/OiyCfYB+v+ARkqKI9nFjVpKhL5CZWVcy1yf7henhujTcalIGENw1dvVQ0u5BAADMajSf29dasv+45alydV4sQqtckswgU5MTacB4FKitq2qkZuT6tBGqrhms0PZU/lHhCvQnmMtaJpQAm82PuJORFGj6L7Yx7lTFYFbexQS6pGOdVeXDJ2rVL7lde9YSc9QyVW3MKH3GrA9h/HBRKqtgjaAHBvHOVf9td3ahIf4s=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Jean-of-the-Lazy-A_538
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy